import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import SelectionGrid from '@/components/SelectionGrid';
import SeasonSelector from '@/components/SeasonSelector';
import Hero from '@/components/Hero';
import { twentyTwoHeroProps } from '@/constants/heroes';
import { twentyTwoSelectionCards } from '@/constants/selectionCards';
import BackButton from '@/components/BackButton';
import { useState } from 'react';

export default function SeasonDatabase() {
  const [season, setSeason] = useState('2021');
  console.log(season);

  return (
    <>
      <Head>
        <title>Grand PrixDB | Season Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={twentyTwoHeroProps.title}
          img={twentyTwoHeroProps.img}
          description={twentyTwoHeroProps.description}
        />
        <div className="flex justify-around items-center">
          <BackButton />
          <SeasonSelector season={season} setSeason={setSeason} />
        </div>
        <SelectionGrid cardProps={twentyTwoSelectionCards} season={season} />
        <Footer />
      </div>
    </>
  );
}
