import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import SelectionGrid from '@/components/SelectionGrid';
import Hero from '@/components/Hero';
import { twentyTwoHeroProps } from '@/constants/heroes';
import { twentyTwoSelectionCards } from '@/constants/selectionCards';
import BackButton from '@/components/BackButton';
import Router from 'next/router';

export default function TwentyTwoSeason() {
  return (
    <>
      <Head>
        <title>Grand PrixDB | 2022 Season</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={twentyTwoHeroProps.title}
          img={twentyTwoHeroProps.img}
          description={twentyTwoHeroProps.description}
        />
        <BackButton />
        <SelectionGrid cardProps={twentyTwoSelectionCards} />
        <Footer />
      </div>
    </>
  );
}
