import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import SelectionGrid from '@/components/SelectionGrid';
import Hero from '@/components/Hero';
import { twentyThreeHeroProps } from '@/constants/heroes';
import { twentyThreeSelectionCards } from '@/constants/selectionCards';
import BackButton from '@/components/BackButton';

export default function TwentyTwoSeason() {
  return (
    <>
      <Head>
        <title>Grand PrixDB | 2023 Season</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={twentyThreeHeroProps.title}
          img={twentyThreeHeroProps.img}
          description={twentyThreeHeroProps.description}
        />
        <BackButton />
        <SelectionGrid cardProps={twentyThreeSelectionCards} />
        <Footer />
      </div>
    </>
  );
}
