import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import SelectionGrid from '@/components/SelectionGrid';
import { currentHeroProps } from '@/constants/heroes';
import { twentyThreeSelectionCards } from '@/constants/selectionCards';

export default function Home() {
  return (
    <>
      <Head>
        <title>Grand PrixDB | 2023 Season</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={currentHeroProps.title}
          img={currentHeroProps.img}
          description={currentHeroProps.description}
        />

        <SelectionGrid cardProps={twentyThreeSelectionCards} />
        <Footer />
      </div>
    </>
  );
}
