import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import { homeHeroProps } from '@/constants/heroes';

import NewsGrid from '@/components/NewsGrid';

export default function Home() {
  return (
    <>
      <Head>
        <title>Grand PrixDB | News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={homeHeroProps.title}
          img={homeHeroProps.img}
          description={homeHeroProps.description}
        />
        <NewsGrid />
        <Footer />
      </div>
    </>
  );
}
