import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Hero from '@/components/Hero';
import News from '@/components/News';
import Footer from '@/components/Footer';

export default function Home() {
  const homeHeroProps = {
    title: (
      <div>
        Grand Prix<span className="text-info">.DB</span>
      </div>
    ),
    img: 'https://wallpapercave.com/wp/wp10985103.jpg',
    description: 'The Formula 1 database for all F1 news and statistics.',
  };

  return (
    <>
      <Head>
        <title>Grand PrixDB | News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        <Hero
          title={homeHeroProps.title}
          img={homeHeroProps.img}
          description={homeHeroProps.description}
        />
        <News />
        <Footer />
      </div>
    </>
  );
}
